--Netflix Project
DROP TABLE IF EXISTS NETFLIX;

CREATE TABLE NETFLIX (
	SHOW_ID VARCHAR(6),
	TYPE VARCHAR(10),
	TITLE VARCHAR(150),
	DIRECTOR VARCHAR(208),
	CASTS VARCHAR(1000),
	COUNTRY VARCHAR(150),
	DATE_ADDED VARCHAR(50),
	RELEASE_YEAR INT,
	RATING VARCHAR(10),
	DURATION VARCHAR(15),
	LISTED_IN VARCHAR(100),
	DESCRIPTION VARCHAR(250)
);
SELECT
	*
FROM
	NETFLIX;

SELECT
	 COUNT(*) AS TOTAL_CONTENT
FROM NETFLIX;

SELECT
	DISTINCT TYPE
FROM
	NETFLIX;

-- 15 BUSINESS PROBLEMS 

--Q1. COUNT THE NUMBER OF MOVIES AND TV SHOW
SELECT
	TYPE,
	COUNT(*) AS TOTAL_CONTENT
FROM NETFLIX
GROUP BY TYPE;

--Q2 FIND THE MOST COMMON RATING FOR MOVIE AND TV SHOW
SELECT 
TYPE,RATING 
FROM
(
SELECT 
TYPE,RATING,
COUNT(*),
RANK() OVER (PARTITION BY TYPE ORDER BY COUNT(*) DESC) AS RANKING
FROM NETFLIX
GROUP BY 1,2
) AS T1
WHERE RANKING =1

--Q3 LIST MOVIES FROM SPECIFIC YEAR (EG 2020)
SELECT
	*
FROM
	NETFLIX
WHERE
	TYPE = 'Movie'
	AND RELEASE_YEAR = '2020';

--Q4 FIND THE TOP 5 COUNTRIES WITH THE MOST VIEWED CONTENT ON NETFLIX
SELECT
	UNNEST(STRING_TO_ARRAY(COUNTRY, ',')) AS NEW_COUNTRY,
	COUNT(SHOW_ID) AS TOTAL_CONTENT
FROM
	NETFLIX
GROUP BY
	1;

--Q5 IDENTIFY THE LONGEST RUNNING MOVIE
SELECT
	*
FROM
	NETFLIX
WHERE
	TYPE = 'Movie'
	AND DURATION = (
		SELECT
			MAX(DURATION)
		FROM
			NETFLIX
	);

--Q6 FIND CONTENT ADDED IN LAST 5 YEARS 
SELECT
	*
FROM
	NETFLIX
WHERE
	TO_DATE(DATE_ADDED, 'MONTH,DD,YYYY') >= CURRENT_DATE - INTERVAL '5 YEARS';

--Q7 FIND ALL THE MOVIES/TV SHOWS BY DIRECTOR 'RAJIV CHILAKA' 
SELECT
	*
FROM
	NETFLIX
WHERE
	DIRECTOR ILIKE '%RAJIV CHILAKA%';

--Q8LIST ALL TV SHOWS WITH MORE THAN 5 SEASONS 
SELECT
	*
FROM
	NETFLIX
WHERE
	TYPE = 'TV Show'
	AND SPLIT_PART(DURATION, ' ', 1)::NUMERIC > 5;

--Q9 COUNT THE NUMBER OF CONTENT IYEMS IN ACH GENRE 
SELECT UNNEST(STRING_TO_ARRAY(LISTED_IN ,',')) AS GENRE,
COUNT(SHOW_ID)
FROM NETFLIX
GROUP BY 1;

--Q10 FIND EACH YEAR  AND THE AVERAGE NUMBERS OF CONTENT RELEASE BY INDIA ON NETFLIX.
-- RETURN  TOP 5 WITH HIGHEST AVG CONTENT RELEASE
SELECT 
EXTRACT(YEAR FROM TO_DATE(DATE_ADDED,'MONTH,DD,YYYY')) AS YEAR, 
COUNT(*) AS YEARLY_CONTENT,
ROUND(
COUNT(*) :: NUMERIC/(SELECT COUNT(*) FROM NETFLIX WHERE COUNTRY ='India'):: NUMERIC*100,2) 
AS AVD_CONTENT_PER_YEAR
FROM NETFLIX
WHERE COUNTRY ='India'
GROUP BY 1;

--Q11 LIST ALL  MOVIES THAT ARE DOCUMNETARIES 
SELECT * FROM NETFLIX
 WHERE LISTED_IN ILIKE '%documentaries%' ;
 
 --Q12 FIND ALL CONTENT WITHOUT A DIRECTOR
 SELECT * FROM NETFLIX
 WHERE DIRECTOR IS NULL;

--Q13FIND HOW MANY MOVIES ACTOR "SALMAN KHAN " APPEARED IN LAST 10 YEARS 
SELECT * FROM NETFLIX 
WHERE CASTS ILIKE '%Salman Khan%' 
AND 
RELEASE_YEAR > EXTRACT( YEAR FROM CURRENT_DATE) -10;

-- Q14 FIND TOP 10 ACTORS WHO HAVE APPEAREDIN THE HIGHEST NO OF  MOVIES IN INDIA
SELECT
UNNEST(STRING_TO_ARRAY(CASTS,',')) AS ACTORS,
COUNT(*) AS TOTAL_CONTENT
FROM NETFLIX
WHERE COUNTRY ILIKE '%india%'
GROUP BY 1
ORDER BY 2 DESC 
LIMIT 10;

--Q15 CATEGORIZE THE CONTENT  BASED ON THE PRESENCE OF THE KEYWORDS 'KILL','VIOLENCE'IN 
-- DESCRIPTION FIELD . LABEL CONTENT CONTAINING  THESE KEYWORDS AS BAD & ALL OTHER CONTENT AS
--  'GOOD'. COUNT HOW AMNY ITEMS INTO EACH CATEGORY 

WITH NEW_TABLE 
AS (
SELECT*,

CASE 
WHEN
    DESCRIPTION ILIKE '%kill%'
	OR
	DESCRIPTION ILIKE '%violence%' THEN 'BAD_CONTENT'
	ELSE 'GOOD_CONTENT'
END CATEGORY
FROM NETFLIX
)
SELECT 
CATEGORY ,COUNT(*) AS TOTAL_CONTENT
FROM NEW_TABLE
GROUP BY 1;

	



